apiVersion: v1
kind: Service
metadata:
  name: {{ include "booking-service.fullname" . }}-{{ .Values.version }}
  labels:
    app: booking-service
    version: {{ .Values.version | quote }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: booking-service
    version: {{ .Values.version | quote }}
